version: "3"
services:
  mongodb:
    image: arcanjoqueiroz/mongo:4.0.17
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - $HOME/docker/mongodb/data:/data/db      
    env_file:
      - ./mongodb.env
    
    
